name: CI/CD Pipeline

# Ejecutar en push o pull request en las ramas especificadas
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define los jobs (tareas) del pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js (puedes cambiar según tu proyecto)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar pruebas
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Depende de que el job 'build' termine correctamente

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Desplegar (puedes usar SSH, FTP, o una acción personalizada)
      - name: Deploy to server
        run: echo "Despliegue exitoso"  # Cambiar por tu script de despliegue
